/**
 * Disclaimer block rendered inside every document preview.
 *
 * Wrapped in the `[data-nda-block]` selector so `lib/pdf.ts` captures
 * it and it lands on page 1 of every downloaded PDF.
 */

import { NDA_BLOCK_ATTR } from "@/lib/nda-selectors";

export function DocumentDisclaimer() {
  const props = { [NDA_BLOCK_ATTR]: "" };
  return (
    <div {...props} className="mb-3">
      <div
        style={{
          border: "2px solid #ecad0a",
          backgroundColor: "#fff7e0",
          padding: "10px 14px",
          fontFamily: '"Times New Roman", Times, serif',
          fontSize: "10pt",
          lineHeight: 1.4,
          color: "#032147",
        }}
      >
        <div
          style={{
            fontWeight: 700,
            letterSpacing: "0.05em",
            marginBottom: "4px",
            fontSize: "10.5pt",
          }}
        >
          DRAFT — SUBJECT TO LEGAL REVIEW
        </div>
        <p style={{ margin: 0 }}>
          This document was generated by an AI assistant and has not been
          reviewed by a licensed attorney. It is provided for informational
          purposes only, does not constitute legal advice, and is not a
          substitute for review by qualified counsel before execution.
        </p>
      </div>
    </div>
  );
}
